### ISSUE TITLE
server.js not load

### ISSUE THREAD

**Issue by troyam** [Glavin001/Leopold#44]
```
node server/server.js
speechToText  temp/rec.flac
Thu Jun 28 2018 00:20:11 GMT-0300 (-03) Server is listening on port 1337
undefined
/Users/marcosporto/NodeJS/Leopold/server/server.js:74
                "file": restler.file(audioFile, null, stats.size, null, "audio/flac")
                                                            ^

TypeError: Cannot read property 'size' of undefined
    at /Users/marcosporto/NodeJS/Leopold/server/server.js:74:61
    at FSReqWrap.oncomplete (fs.js:153:21)
```

**Comment by Glavin001** [comment]
Hi @torianBr . Thank you for your interest in Leopold. Unfortunately, I am no longer maintaining Leopold and unable to debug any related issues.
If you figure out the problem, feel free to comment back here and/or create a Pull Request. Thanks!

**Comment by troyam** [comment]
Hi Gavin, answering your question: at this point I'm stuck with speech-to-text. But It's not your project it's my own. I'm trying to create this recognize function in a different way. I know I don't need to re-create the road but I'm doing something different. Thank's!
